name: ardrive_http
description: ArDrive Network abstractions
version: 1.1.3
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: 3.3.9

script_runner:
  shell:
    default: /bin/sh
    windows: cmd.exe
    macos: /bin/sh
    linux: /bin/sh
  line_length: 80
  scripts:
    - webserver: dart run test/webserver.dart
    - test-web: scr webserver & sleep 10 && flutter test --platform chrome
    - test-vm: scr webserver & sleep 10 && flutter test
    - test: scr test-vm && scr test-web

dependencies:
  dio: ^5.0.0
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  isolated_worker: ^0.1.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  async: ^2.9.0
